2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_setup.py:_flush():67] Configure stats pid to 7972
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\settings
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_184345-iweeysh2\logs\debug.log
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_184345-iweeysh2\logs\debug-internal.log
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:init():761] calling init triggers
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:init():784] starting backend
2025-03-06 18:43:45,709 INFO    MainThread:7972 [wandb_init.py:init():788] sending inform_init request
2025-03-06 18:43:45,733 INFO    MainThread:7972 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-06 18:43:45,733 INFO    MainThread:7972 [wandb_init.py:init():803] backend started and connected
2025-03-06 18:43:45,734 INFO    MainThread:7972 [wandb_init.py:init():896] updated telemetry
2025-03-06 18:43:45,771 INFO    MainThread:7972 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-06 18:43:47,310 INFO    MainThread:7972 [wandb_init.py:init():995] starting run threads in backend
2025-03-06 18:43:47,536 INFO    MainThread:7972 [wandb_run.py:_console_start():2377] atexit reg
2025-03-06 18:43:47,536 INFO    MainThread:7972 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-06 18:43:47,536 INFO    MainThread:7972 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-06 18:43:47,536 INFO    MainThread:7972 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-06 18:43:47,538 INFO    MainThread:7972 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-06 18:43:54,058 INFO    MainThread:7972 [wandb_agent.py:run():220] Running runs: []
2025-03-06 18:43:54,661 INFO    MainThread:7972 [wandb_agent.py:_process_command():316] Agent received command: run
2025-03-06 18:43:54,672 INFO    MainThread:7972 [wandb_agent.py:_command_run():349] Agent starting run with config:
	activation_function: sigmoid
	batch_size: 16
	initialisation: random
	learning_rate: 0.001
	number_of_epochs: 5
	number_of_hidden_layers: 3
	size_of_every_hidden_layer: 128
2025-03-06 18:43:54,674 INFO    MainThread:7972 [wandb_agent.py:_command_run():416] About to run command: python main.py
2025-03-06 18:43:59,682 INFO    MainThread:7972 [wandb_agent.py:run():220] Running runs: ['wiurz511']
2025-03-06 18:44:05,109 INFO    MainThread:7972 [wandb_agent.py:run():255] Cleaning up finished run: wiurz511
2025-03-06 18:44:05,111 WARNING MsgRouterThr:7972 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-06 18:44:05,136 INFO    MsgRouterThr:7972 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-06 18:44:07,348 INFO    MainThread:7972 [wandb_agent.py:_process_command():316] Agent received command: run
2025-03-06 18:44:07,350 INFO    MainThread:7972 [wandb_agent.py:_command_run():349] Agent starting run with config:
	activation_function: sigmoid
	batch_size: 128
	initialisation: random
	learning_rate: 0.001
	number_of_epochs: 5
	number_of_hidden_layers: 3
	size_of_every_hidden_layer: 128
2025-03-06 18:44:07,353 INFO    MainThread:7972 [wandb_agent.py:_command_run():416] About to run command: python main.py
2025-03-06 18:44:12,366 INFO    MainThread:7972 [wandb_agent.py:run():220] Running runs: ['jdclp01f']
2025-03-06 18:44:17,743 INFO    MainThread:7972 [wandb_agent.py:run():255] Cleaning up finished run: jdclp01f
