2025-03-06 22:28:57,666 INFO    StreamThr :24924 [internal.py:wandb_internal():83] W&B internal server running at pid: 24924, started at: 2025-03-06 22:28:57.664003
2025-03-06 22:28:57,670 INFO    WriterThread:24924 [datastore.py:open_for_write():87] open: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\run-qrblpzb9.wandb
2025-03-06 22:28:58,807 INFO    SenderThread:24924 [dir_watcher.py:__init__():211] watching files in: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files
2025-03-06 22:28:58,807 INFO    SenderThread:24924 [sender.py:_start_run_threads():1133] run started: qrblpzb9 with start time 1741280337.664003
2025-03-06 22:28:59,760 INFO    HandlerThread:24924 [system_monitor.py:start():187] Starting system monitor
2025-03-06 22:28:59,760 INFO    SystemMonitor:24924 [system_monitor.py:_start():151] Starting system asset monitoring threads
2025-03-06 22:28:59,760 INFO    HandlerThread:24924 [system_monitor.py:probe():207] Collecting system info
2025-03-06 22:28:59,776 INFO    SystemMonitor:24924 [interfaces.py:start():186] Started cpu monitoring
2025-03-06 22:28:59,776 INFO    SystemMonitor:24924 [interfaces.py:start():186] Started disk monitoring
2025-03-06 22:28:59,778 INFO    SystemMonitor:24924 [interfaces.py:start():186] Started gpu monitoring
2025-03-06 22:28:59,798 INFO    SystemMonitor:24924 [interfaces.py:start():186] Started memory monitoring
2025-03-06 22:28:59,836 INFO    SystemMonitor:24924 [interfaces.py:start():186] Started network monitoring
2025-03-06 22:28:59,838 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:28:59,838 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:28:59,978 INFO    HandlerThread:24924 [system_monitor.py:probe():217] Finished collecting system info
2025-03-06 22:28:59,978 INFO    HandlerThread:24924 [system_monitor.py:probe():220] Publishing system info
2025-03-06 22:28:59,978 INFO    HandlerThread:24924 [system_monitor.py:probe():222] Finished publishing system info
2025-03-06 22:28:59,993 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-metadata.json with policy now
2025-03-06 22:29:00,847 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-metadata.json
2025-03-06 22:29:00,848 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\requirements.txt
2025-03-06 22:29:01,384 INFO    wandb-upload_0:24924 [upload_job.py:push():130] Uploaded file C:\Users\shrey\AppData\Local\Temp\tmphqkyapdswandb\0uj34znv-wandb-metadata.json
2025-03-06 22:29:10,472 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:29:10,476 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:10,476 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:20,571 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:29:20,571 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:20,571 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:30,704 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:29:30,704 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:30,704 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:32,165 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\config.yaml
2025-03-06 22:29:41,259 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:29:41,259 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:41,259 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:51,790 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:29:51,793 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:29:51,793 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:02,389 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:02,393 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:02,393 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:13,007 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:13,007 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:13,007 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:23,635 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:23,638 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:23,638 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:34,262 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:34,262 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:34,262 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:45,008 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:45,012 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:45,012 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:55,643 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:30:55,645 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:30:55,645 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:01,685 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:31:04,036 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB499D0>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:31:06,764 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:31:06,768 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:06,768 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:08,124 INFO    SenderThread:24924 [retry.py:__call__():175] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002603BB60350>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB60350>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\retry.py", line 134, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\internal\internal_api.py", line 398, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB60350>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)"))
2025-03-06 22:31:08,443 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB4A650>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:31:17,450 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BC46990>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:31:17,745 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:31:17,745 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:17,745 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:28,708 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:31:28,710 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:28,710 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:33,912 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BC52450>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:31:39,676 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:31:39,678 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:39,678 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:50,552 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:31:50,568 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:31:50,568 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:00,693 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:00,693 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:00,693 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:08,136 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB33950>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:32:10,838 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:10,840 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:10,840 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:21,523 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:21,537 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:21,537 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:32,170 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:32,170 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:32,170 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:42,746 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:42,746 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:42,746 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:53,410 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:32:53,410 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:32:53,410 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:04,057 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:04,064 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:04,064 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:14,655 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:14,655 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:14,655 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:24,893 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB33E10>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:33:25,247 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:25,250 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:25,250 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:35,838 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:35,843 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:35,843 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:46,797 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:46,799 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:46,799 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:57,772 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:33:57,772 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:33:57,772 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:08,771 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:34:08,778 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:08,778 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:19,726 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:34:19,726 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:19,726 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:30,663 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:34:30,668 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:30,669 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:41,672 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:34:41,678 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:41,678 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:52,663 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:34:52,668 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:34:52,668 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:03,638 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:03,638 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:03,638 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:14,587 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:14,587 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:14,587 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:25,538 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:25,541 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:25,541 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:36,125 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:36,125 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:36,125 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:47,142 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:47,144 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:47,144 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:58,053 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:35:58,055 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:35:58,055 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:03,361 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BB49C90>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:36:08,975 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:36:08,977 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:08,977 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:19,909 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:36:19,909 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:19,909 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:30,812 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:36:30,815 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:30,815 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:41,713 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:36:41,715 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:41,715 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:52,780 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:36:52,782 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:36:52,782 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:03,727 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:03,729 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:03,729 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:14,643 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:14,647 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:14,647 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:25,558 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:25,570 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:25,570 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:36,503 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:36,511 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:36,511 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:47,477 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:47,477 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:47,477 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:58,443 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:37:58,445 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:37:58,445 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:09,355 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:38:09,357 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:09,357 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:20,276 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:38:20,278 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:20,278 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:31,202 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:38:31,219 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:31,219 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:42,094 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:38:42,094 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:42,094 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:52,947 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:38:52,947 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:38:52,947 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:03,800 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:03,802 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:03,802 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:14,641 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:14,641 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:14,641 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:25,505 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:25,505 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:25,505 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:36,357 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:36,357 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:36,357 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:47,209 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:47,209 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:47,209 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:58,036 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:39:58,046 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:39:58,046 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:08,875 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:40:08,875 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:08,875 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:19,715 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:40:19,715 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:19,715 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:27,019 WARNING FileStreamThread:24924 [file_stream.py:request_with_retry():674] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002603BC534D0>: Failed to resolve 'api.wandb.ai' ([Errno 11001] getaddrinfo failed)")). func: <bound method Session.post of <requests.sessions.Session object at 0x000002603B2E2490>>, args: ('https://api.wandb.ai/files/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 41, 'content': ['{"system.disk.\\\\.usagePercent": 90.7, "system.disk.\\\\.usageGB": 414.2, "system.disk.in": 35.92, "system.disk.out": 949.17, "_wandb": true, "_timestamp": 1741280429.972236, "_runtime": 92.308233}', '{"system.proc.memory.availableMB": 2153.53, "system.memory": 86.6, "system.proc.memory.rssMB": 1121.11, "system.proc.memory.percent": 6.95, "_wandb": true, "_timestamp": 1741280430.048497, "_runtime": 92.384494}', '{"system.network.sent": 559704.0, "system.network.recv": 206915.0, "_wandb": true, "_timestamp": 1741280430.252125, "_runtime": 92.588122}', '{"system.gpu.0.memoryAllocated": 6.91, "system.gpu.0.memoryAllocatedBytes": 148443136.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 84.0, "_wandb": true, "_timestamp": 1741280434.262994, "_runtime": 96.598991}', '{"system.cpu": 12.54, "system.proc.cpu.threads": 22, "_wandb": true, "_timestamp": 1741280439.983718, "_runtime": 102.319715}']}}, 'dropped': 0}}
2025-03-06 22:40:30,581 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:40:30,583 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:30,583 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:41,440 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:40:41,440 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:41,440 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:52,271 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:40:52,271 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:40:52,271 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:03,118 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:03,118 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:03,118 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:13,970 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:13,972 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:13,972 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:24,826 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:24,826 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:24,826 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:35,654 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:35,654 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:35,654 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:46,507 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:46,507 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:46,507 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:57,375 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:41:57,375 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:41:57,375 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:07,549 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:42:07,552 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:07,552 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:18,419 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:42:18,421 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:18,421 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:29,305 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:42:29,305 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:29,305 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:40,214 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:42:40,216 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:40,216 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:51,078 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:42:51,081 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:42:51,081 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:01,957 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:01,957 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:01,957 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:12,782 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:12,791 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:12,792 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:22,852 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:22,854 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:22,854 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:32,969 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:32,970 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:32,970 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:43,074 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:43,075 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:43,076 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:53,667 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:43:53,671 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:43:53,671 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:04,177 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:04,179 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:04,179 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:14,702 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:14,702 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:14,702 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:25,207 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:25,209 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:25,209 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:35,729 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:35,733 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:35,733 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:46,249 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:46,251 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:46,251 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:56,759 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:44:56,759 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:44:56,759 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:07,281 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:45:07,281 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:07,281 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:17,810 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:45:17,810 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:17,810 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:28,841 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:45:28,842 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:28,843 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:39,737 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:45:39,739 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:39,740 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:50,635 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:45:50,639 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:45:50,639 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:01,540 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:46:01,540 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:01,540 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:12,455 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:46:12,458 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:12,458 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:22,534 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:46:22,534 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:22,534 ERROR   gpu       :24924 [interfaces.py:monitor():140] Failed to sample metric: Not Supported
2025-03-06 22:46:30,287 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,293 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,294 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,296 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,306 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,308 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,311 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,313 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,323 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,325 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,326 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,328 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,333 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,335 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,337 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,339 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,346 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,347 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,348 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,349 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,349 INFO    SenderThread:24924 [sender.py:send_exit():553] handling exit code: 0
2025-03-06 22:46:30,349 INFO    SenderThread:24924 [sender.py:send_exit():555] handling runtime: 591
2025-03-06 22:46:30,349 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,349 INFO    SenderThread:24924 [sender.py:send_exit():561] send defer
2025-03-06 22:46:30,365 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 0
2025-03-06 22:46:30,365 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 0
2025-03-06 22:46:30,365 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 1
2025-03-06 22:46:30,365 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 1
2025-03-06 22:46:30,381 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 1
2025-03-06 22:46:30,381 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 2
2025-03-06 22:46:30,382 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 2
2025-03-06 22:46:30,382 INFO    HandlerThread:24924 [system_monitor.py:finish():196] Stopping system monitor
2025-03-06 22:46:30,399 INFO    HandlerThread:24924 [interfaces.py:finish():198] Joined cpu monitor
2025-03-06 22:46:30,400 INFO    HandlerThread:24924 [interfaces.py:finish():198] Joined disk monitor
2025-03-06 22:46:30,794 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-summary.json
2025-03-06 22:46:30,796 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\output.log
2025-03-06 22:46:30,904 ERROR   gpu       :24924 [interfaces.py:aggregate():157] Failed to serialize metric: division by zero
2025-03-06 22:46:30,905 INFO    HandlerThread:24924 [interfaces.py:finish():198] Joined gpu monitor
2025-03-06 22:46:30,905 INFO    HandlerThread:24924 [interfaces.py:finish():198] Joined memory monitor
2025-03-06 22:46:30,906 INFO    HandlerThread:24924 [interfaces.py:finish():198] Joined network monitor
2025-03-06 22:46:30,907 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 2
2025-03-06 22:46:30,907 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 3
2025-03-06 22:46:30,908 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 3
2025-03-06 22:46:30,909 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 3
2025-03-06 22:46:30,909 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 4
2025-03-06 22:46:30,909 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 4
2025-03-06 22:46:30,910 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 4
2025-03-06 22:46:30,910 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 5
2025-03-06 22:46:30,910 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 5
2025-03-06 22:46:30,912 INFO    SenderThread:24924 [sender.py:_save_file():1402] saving file wandb-summary.json with policy end
2025-03-06 22:46:30,913 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 5
2025-03-06 22:46:30,913 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 6
2025-03-06 22:46:30,913 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 6
2025-03-06 22:46:30,914 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 6
2025-03-06 22:46:30,914 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 7
2025-03-06 22:46:30,915 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 7
2025-03-06 22:46:30,915 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 7
2025-03-06 22:46:31,800 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-summary.json
2025-03-06 22:46:32,353 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 8
2025-03-06 22:46:32,353 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 8
2025-03-06 22:46:32,353 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 8
2025-03-06 22:46:32,353 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 9
2025-03-06 22:46:32,353 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 9
2025-03-06 22:46:32,353 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 9
2025-03-06 22:46:32,353 INFO    SenderThread:24924 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-06 22:46:32,801 INFO    Thread-16 :24924 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\output.log
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():388] scan: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():402] scan save: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\config.yaml config.yaml
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():402] scan save: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\output.log output.log
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():402] scan save: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\requirements.txt requirements.txt
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():402] scan save: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-metadata.json wandb-metadata.json
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [dir_watcher.py:finish():402] scan save: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-summary.json wandb-summary.json
2025-03-06 22:46:32,802 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 10
2025-03-06 22:46:32,802 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 10
2025-03-06 22:46:32,819 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 10
2025-03-06 22:46:32,819 INFO    SenderThread:24924 [file_pusher.py:finish():169] shutting down file pusher
2025-03-06 22:46:33,218 ERROR   wandb-upload_0:24924 [internal_api.py:upload_file():3022] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/me21b138-indian-institute-of-technology-madras/my-awesome-project/qrblpzb9/config.yaml?Expires=1741367792&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NDYa6K5AioWt4iLVl3tiC%2B%2B2wUgM6kiXQ4g%2BR9WZXDx6a%2FeDYUSStAho9Q044B3q93H%2F8wE7eoiec1smIGj%2FqtpB%2FTnf9yDv5I9Aq39TVa%2Bn%2Bdjy5vtyx5tc8FdRlgJ50h2q%2BKMpdUp1ZxfYzJts9OPgByN4JbpJ8LXogPuu4Rawmx8N7q8MEE3V2tUG5MtRGhIjLTtQ2EiiAbO82KpqWdWHb0UbDKkO%2FSSGZm0uCLA7Rj3C7XhBNpSfJ2BcW6QLeHae5BMvzoTApXwOMLdq9c3ODebQqWjvUuKeE13qWkstXoutatDbxGUPQomiOBsyT8oka7QVR9tgW%2FzdttSoEg%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-06 22:46:33,218 ERROR   wandb-upload_0:24924 [internal_api.py:upload_file():3024] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '867'}
2025-03-06 22:46:33,218 ERROR   wandb-upload_0:24924 [internal_api.py:upload_file():3026] upload_file response body: ''
2025-03-06 22:46:33,768 INFO    wandb-upload_3:24924 [upload_job.py:push():130] Uploaded file C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\wandb-summary.json
2025-03-06 22:46:33,768 INFO    wandb-upload_2:24924 [upload_job.py:push():130] Uploaded file C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\requirements.txt
2025-03-06 22:46:34,637 INFO    wandb-upload_1:24924 [upload_job.py:push():130] Uploaded file C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\output.log
2025-03-06 22:46:34,789 INFO    wandb-upload_0:24924 [upload_job.py:push():130] Uploaded file C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\files\config.yaml
2025-03-06 22:46:34,995 INFO    Thread-15 (_thread_body):24924 [sender.py:transition_state():581] send defer: 11
2025-03-06 22:46:34,995 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 11
2025-03-06 22:46:34,995 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 11
2025-03-06 22:46:34,995 INFO    SenderThread:24924 [file_pusher.py:join():175] waiting for file pusher
2025-03-06 22:46:34,995 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 12
2025-03-06 22:46:34,995 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 12
2025-03-06 22:46:34,995 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 12
2025-03-06 22:46:34,995 INFO    SenderThread:24924 [file_stream.py:finish():601] file stream finish called
2025-03-06 22:46:36,011 INFO    SenderThread:24924 [file_stream.py:finish():605] file stream finish is done
2025-03-06 22:46:36,011 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 13
2025-03-06 22:46:36,011 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 13
2025-03-06 22:46:36,011 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 13
2025-03-06 22:46:36,011 INFO    SenderThread:24924 [sender.py:transition_state():581] send defer: 14
2025-03-06 22:46:36,011 INFO    HandlerThread:24924 [handler.py:handle_request_defer():188] handle defer: 14
2025-03-06 22:46:36,011 INFO    SenderThread:24924 [sender.py:send_request_defer():577] handle sender defer: 14
2025-03-06 22:46:36,011 INFO    MainThread:24924 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-03-06 22:46:36,011 INFO    MainThread:24924 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-03-06 22:46:36,011 INFO    MainThread:24924 [wandb_run.py:_footer_sync_info():3919] logging synced files
2025-03-06 22:46:36,028 INFO    HandlerThread:24924 [handler.py:finish():897] shutting down handler
2025-03-06 22:46:37,028 INFO    SenderThread:24924 [sender.py:finish():1580] shutting down sender
2025-03-06 22:46:37,028 INFO    WriterThread:24924 [datastore.py:close():296] close: C:\Users\shrey\Desktop\ACAD\DL\DA6401_AS1\wandb\run-20250306_222857-qrblpzb9\run-qrblpzb9.wandb
2025-03-06 22:46:37,028 INFO    MsgRouterThr:24924 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
2025-03-06 22:46:37,028 INFO    SenderThread:24924 [file_pusher.py:finish():169] shutting down file pusher
2025-03-06 22:46:37,028 INFO    SenderThread:24924 [file_pusher.py:join():175] waiting for file pusher
